#1675 waived interview other info fields
Hennepin-County/MAXIS-scripts pull request #1684
Opened 2024-02-16 22:21 UTC by courtrightd

Adds two fields to the information needed dialog that allow the user to enter additional information that comes up in the conversation.
These fields are added to the information provided case note. If left blank, nothing is added to note.

2024-02-20 19:58 UTC, MeganGeissler requested changes
Added a few comments to review! Otherwise the casenote looks good.

2024-02-20 19:58 UTC, MeganGeissler commented on notes/snap-waived-interview.vbs
> +	If page_display <> q_page_xtra Then PushButton 290, 350, 50, 15, "Next", next_btn
Verification buttons on the xtra dialog do not provide a dialog to enter information. Seems like it's looping back to the xtra dialog without providing verf dialog.

2024-02-22 17:42 UTC, IlseFerris requested changes
The dimming worked for the contact information. 
I was still unable to get the other information verifications to pull through.

2024-02-24 16:12 UTC, courtrightd commented
Updates made that seem to have fixed the verifications pulling through for me....

2024-02-26 17:58 UTC, C-Love approved these changes

2024-02-26 17:59 UTC, C-Love commented
I've reviewed the code and it all appears solid. I have not had time to run the script as a test. 

We have a separate syntax bug reported, so I have added this fix to the branch and I am pulling it all in together.

2024-02-26 17:59 UTC, merged