#1685 New Script - ADMIN - Individual On Demand Notices
Hennepin-County/MAXIS-scripts pull request #1700
Opened 2024-02-23 18:57 UTC by C-Love

This is the new script creation. We will have another pull request with updates to CLOS, and to retire the 3 scripts this new script replaces.

2024-03-04 23:44 UTC, IlseFerris commented on admin/individual-on-demand-notices.vbs
> +	MsgBox "notc_confirm - " & notc_confirm
Line 452 - msgbox needs to be removed.

2024-03-04 23:49 UTC, IlseFerris commented on admin/individual-on-demand-notices.vbs
> +			If IsDate(interview_end_date) = False Then err_msg = err_msg & vbCr & "* Enter the date the interview is due by for the Notice to the resident."
Line 350: Wrong variable here, not allowing me to pass.

2024-03-04 23:49 UTC, IlseFerris requested changes
See comments below. I was able to test all options, and all passed save for RECERT - NOMI.

2024-03-05 15:08 UTC, C-Love commented
Updated with changes requested.

2024-03-05 16:07 UTC, IlseFerris approved these changes
I fudged the nomi date to test this and it worked as intended. I approve thee!

2024-03-06 15:43 UTC, merged