#892 NOTES - INTERVIEW, Add emergency questions
Hennepin-County/MAXIS-scripts pull request #2054
Opened 2024-10-23 17:18 UTC by MDR22

Added emergency questions to script:
- Added separate dialog tab for emergency questions with error handling
- Updated save your work functionality for emergency questions
- Updated script lowdown to include emergency questions
- Responses to emergency questions will write to PDF and CASE/NOTE

2024-10-23 18:58 UTC, MeganGeissler approved these changes
Works well! - since the EMER error handling is only applicable if the EMER box being checked at the beginning of the script, wondering if we only want the EMER Q tab to only show up when the EMER box is checked, or do we always want it available?

2024-10-23 19:03 UTC, MDR22 commented
> Works well! - since the EMER error handling is only applicable if the EMER box being checked at the beginning of the script, wondering if we only want the EMER Q tab to only show up when the EMER box is checked, or do we always want it available?

My understanding is that we want the questions to be required if the EMER box is checked, but otherwise they are optional so that they still appear if the resident reports an emergency during the interview.

2024-10-23 20:13 UTC, courtrightd reviewed
Combobox for emergency_type should have "Select or type..."
When typing in my own answer to that field, it loses it when going to different dialog, and then get the must complete questions error. Perhaps remove that from required fields, so that if the "emer" doesn't fit within program policy we can explain it in the discussion box.

2024-10-24 13:02 UTC, MDR22 commented
> Combobox for emergency_type should have "Select or type..." When typing in my own answer to that field, it loses it when going to different dialog, and then get the must complete questions error. Perhaps remove that from required fields, so that if the "emer" doesn't fit within program policy we can explain it in the discussion box.

Switched combobox to have 'Select or type' option. Resolved issue of script resetting custom combobox entry when navigating away from EMER Q dialog.

2024-10-24 14:04 UTC, courtrightd approved these changes
Approved!

2024-10-25 16:45 UTC, C-Love requested changes
We should try to simplify the options for the interview question.

2024-10-30 13:55 UTC, MDR22 commented on notes/interview.vbs
> +			ComboBox 190, 40, 90, 25, "Select or type"+chr(9)+"Bus Tickets"+chr(9)+"Damage Deposit"+chr(9)+"Eviction Notice"+chr(9)+"First Month's Rent"+chr(9)+"Foreclosure"+chr(9)+"Home Repairs"+chr(9)+"Movi
Updated the dialog fields accordingly - thanks!

2024-10-30 16:12 UTC, courtrightd approved these changes
Thanks for the updates!

2024-10-30 16:14 UTC, merged